### ISSUE TITLE
Feat: Add textarea for adding co-authors to talks by email address (Intermediate)

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#10]
Add textareas to add and edit co-athors by email

![traveller coauthor new talk](https://user-images.githubusercontent.com/22630684/132217218-6e09d027-be4d-48d4-94d7-491fa38f6c51.png)

![traveller leaderboard talk actions add coautho 1r](https://user-images.githubusercontent.com/22630684/132217161-b5be8d7b-f707-48fe-9ade-46508c7d103e.png)

In modules/conf/models.py, Talk has author_list which has attribute authors

But, it is not used. We need the text areas on these 2 views:

http://127.0.0.1:5000/cfp/2021/talk/1/final_talk_action

http://127.0.0.1:5000/y/2021/cfp/

**Comment by stwins60** [comment]
can i work on this

**Comment by Abdur-rahmaanJ** [comment]
@stwins60 Assigned!
