### ISSUE TITLE
Chore: The Big Test List

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#12]
- [ ] modules/cfp
- [ ] modules/conf
- [ ] modules/profile
- [ ] modules/resource
- [ ] modules/www
- [ ] modules/y

While waiting for coverage integration

**Comment by michaelbukachi** [comment]
Hey @Abdur-rahmaanJ, I'd love to start working on some of these.

**Comment by Abdur-rahmaanJ** [comment]
@michaelbukachi You want to break up this issue into 6 issues? If yes do so then ill close this one. You then take whichever you want!

**Comment by michaelbukachi** [comment]
@Abdur-rahmaanJ Yes. That would be better so that there's less to review.

**Comment by Abdur-rahmaanJ** [comment]
Ok!

**Comment by Abdur-rahmaanJ** [comment]
@michaelbukachi Done!
