### ISSUE TITLE
Chore: Run tests before PR

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#13]
@rehmanis will look into it!

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ I might not have time these day to do it but I can review it if anyone takes this on. For anyone who is taking this on, all of this has been done here https://github.com/shopyo/shopyo so you can use that as a reference.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis if you can write what to do in here ^^ that'd be great!

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ just made a PR for now. Commented out all the tests failing since you changed few things without updating tests.
