### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#140]
see https://validator.w3.org/nu/?doc=https%3A%2F%2Fflaskcon.com%2Fy%2F2021%2F

**Comment by tduck973564** [comment]
I can help out with this, I'm a bit new to open source, the only PR's I have done were helping my friends with their website. What file is this in? I am not familiar with this project.

**Comment by Abdur-rahmaanJ** [comment]
@tduck973564 
Here:

https://github.com/FlaskCon/traveller/blob/dev/traveller/static/themes/front/conftheme/2021/index.html

If you want a normal PR, just edit the file in the web interface

If you want to set up the app, join the Pallets Discord https://discord.gg/pallets then go to #flaskcon-waiting-room then ping @appinv saying that you want to fix the html errors

**Comment by tduck973564** [comment]
Alright, thanks!
