### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by 0x15F9** [FlaskCon/traveller#144]
There should be a contribution guideline to instruct on how to contibute

**Comment by Abdur-rahmaanJ** [comment]
@0x15F9 see README, what did you expect more? git instructions or?

**Comment by 0x15F9** [comment]
I was thinking about following certain conventions for things like commits and branches. But that might deter some people from contributing.

**Comment by Abdur-rahmaanJ** [comment]
@0x15F9 Add them to the readme if you can!
