### ISSUE TITLE
Bug: Author should not be able to tick out himself when editing his talk

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#145]
![talk_author_as_coauthor](https://user-images.githubusercontent.com/22630684/135701511-fd7f9e45-1667-477e-b229-ec24fc06998d.png)

Submitter's mail should not appear

**Comment by 0x15F9** [comment]
Please assign this issue to me :)

**Comment by iSOLveIT** [comment]
@0x15F9 I realised you have been assigned to this issue.
A new bug which is related to this issue has been fixed together with this issue.
Sorry if you have spent time fixing this issue. Thanks
