### ISSUE TITLE
Fix: Front-end: Reviewers too near one another on the front page

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#150]
![reviewers_too_near](https://user-images.githubusercontent.com/22630684/135704175-6ac0af92-9954-4108-b4e2-1c83421dde80.png)

Add margin bottom

**Comment by Abdur-rahmaanJ** [comment]
Use tailwind classes

**Comment by riyaku11** [comment]
I would like to work on this issue

**Comment by Abdur-rahmaanJ** [comment]
@riyaku11 you know Flask?
