### ISSUE TITLE
BugFix: Add flask seed command to seed db

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#24]
Add the

```bash
flask seed
``` 

command to seed the db. Move the codes from [here](https://github.com/FlaskCon/traveller/blob/3e0fa7a568bd703db053a50e52692697e4ede718/traveller/modules/conf/upload.py).

This will move faker to dev_requirements.txt

**Comment by jtrip** [comment]
this should be resolved by #25
