### ISSUE TITLE
Error with command:  python manage.py createconfig

### ISSUE THREAD

**Issue by mohamedmehdigara** [FlaskCon/traveller#3]
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe: can't open file 'C:\Users\Admin\Downloads\traveller\manage.py': [Errno 2] No such file or directory

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara cd into traveller/ once more. there are two folders named traveller
