### ISSUE TITLE
BugFix: End time < start time when building schedule

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#34]
When adding an activity, there is no check that the end time is later than the start time.

![Screenshot from 2021-09-07 10-23-16](https://user-images.githubusercontent.com/9895620/132310922-1eba878d-b621-4dff-a79b-b8c950d4a9f8.png)

**Comment by Abdur-rahmaanJ** [comment]
Time travellers XD

**Comment by kunmi02** [comment]
Hello there,

I will like to work on this issue.

**Comment by jugmac00** [comment]
> Hello @Abdur-rahmaanJ
> 
> I will like to work on this issue.

Go for it! 👍

**Comment by kunmi02** [comment]
I have been facing some issues setting the project.
Find attached the screenshot of the errors
https://drive.google.com/file/d/1BIfVPjHliGzw0xwQYozAuxaKHBXhg7qu/view?usp=sharing

Can anyone help please ?

**Comment by Abdur-rahmaanJ** [comment]
@kunmi02 i don't see a stack trace. Btw you can include screenshots directly in here or ask on discord where you'll have more responses ^^

**Comment by Abdur-rahmaanJ** [comment]
@kunmi02 https://discord.gg/pallets

ping me @ appinv

**Comment by kunmi02** [comment]
I sent you a friend request on discord, kindly accept, please

**Comment by kunmi02** [comment]
KIndly add me to the repo as a contributor please. I am done with the fix but I need access to push

**Comment by jugmac00** [comment]
The common way is to fork the repo and create a pull request. No need to have access in order to contribute.

**Comment by jugmac00** [comment]
fixed by #56 

Thank you!
