### ISSUE TITLE
admin is able to rate talks

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#36]
**repro**

- log in as admin
- rate a talk

=> talks should be only rated by reviewers

**Comment by jugmac00** [comment]
Maybe I get this wrong.

@Abdur-rahmaanJ Who is supposed to rate a talk?

And what is the job of the reviewers?

**Comment by Abdur-rahmaanJ** [comment]
@jugmac00 Reviewers only rate talks XD but like admins should have every powers, bit like how things were at sessionize

**Comment by Abdur-rahmaanJ** [comment]
Let us confirm this with  @davidism
