### ISSUE TITLE
Feat: add delete button for days

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#38]
Currently, after adding a day for a conference, it is not possible to delete it any more

**Comment by Abdur-rahmaanJ** [comment]
In schedule

**Comment by iSOLveIT** [comment]
If I understand you, are you talking about not being able to delete conferences after adding?

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT go to the schedule page. Add a new day. You cannot delete the day. Implement the delete day button

**Comment by iSOLveIT** [comment]
Oh okay, I get it now. There is an issue also that does not allow you to delete conferences after adding.

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT 

![Screenshot_20210907-222837_Samsung Internet](https://user-images.githubusercontent.com/22630684/132393563-e732cc1a-6c35-4b2f-87a2-1f1c6c90537d.jpg)


It has you hace to go to tge dashboard then conf


127.0.0.1:5000/dashboard

login with admin@domain.com | pass

then go to conf

**Comment by iSOLveIT** [comment]
I know it has a delete button but you can not delete the conference.

**Comment by iSOLveIT** [comment]
I think it is an error from my end

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT add one more conference then delete it

**Comment by iSOLveIT** [comment]
It does. Thanks

**Comment by iSOLveIT** [comment]
The conference module has a foreign relationship with both Talks, ReviewList, and Schedule models. I was able to delete the added confernce after I deleted the records from the other modules.

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT its actually a useful feature to have so as not to find a conf gone in a zap. if you add cascade-delete, delete orphan in sqla, all will zap

**Comment by iSOLveIT** [comment]
Yeah found it necessary to have those foreign relationships to prevent all zapping.

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT you managed to do this?

**Comment by iSOLveIT** [comment]
> @iSOLveIT you managed to do this?

@Abdur-rahmaanJ Sent a PR for it
