### ISSUE TITLE
BugFix: Select only one talk when adding to schedule.

### ISSUE THREAD

**Issue by jugmac00** [FlaskCon/traveller#39]
I think there needs to be a list of talks to choose from? @Abdur-rahmaanJ

**Comment by Abdur-rahmaanJ** [comment]
@jugmac00 you add a talk as a speaker. you mean submit a talk or you mean add a talk to schedule?

**Comment by jugmac00** [comment]
Ok, sorry - this is a multiselect!!

But a multiselect is wrong here - you should be only allowed to schedule one talk at a time

![Screenshot from 2021-09-07 11-16-39](https://user-images.githubusercontent.com/9895620/132319192-331b841f-fa5f-4a34-9806-40d724e284fc.png)

**Comment by Abdur-rahmaanJ** [comment]
Actually i thought you could only select one ... maybe we need to enable only one select
