### ISSUE TITLE
Error with command: python manage.py db migrate

### ISSUE THREAD

**Issue by mohamedmehdigara** [FlaskCon/traveller#4]
Error: Path doesn't exist: 'C:\\Users\\Admin\\Downloads\\traveller\\traveller\\migrations'.  Please use the 'init' command to create a new scripts folder.
See you soon!!!

**Comment by Abdur-rahmaanJ** [comment]
What command did you write?

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ  

- There is already a folder named instance inside traveller/traveller.
-  There is already a file named config.py inside traveller/traveller/instance.
- There is already two files named config_demo.json and config.json inside traveller/traveller.
 
What is the full command to initialise? Is it **git init** or **python init** or what?

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara 

then you forgot a step in the readme

`python manage.py initialise`

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ 
Error with the command: **python manage.py initialise**
Traceback (most recent call last):
    from app import app
  File "C:\Users\Admin\Downloads\traveller\traveller\app.py", line 12, in <module>        
    from flask_admin import Admin
ModuleNotFoundError: No module named 'flask_admin'

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara you missed the requirements step from the readme
