### ISSUE TITLE
Chore: update front-end

### ISSUE THREAD

**Issue by miquelvir** [FlaskCon/traveller#61]
The actual front-end looks... _bad_. Let's make it clean, modern, and shiny!

- [Discussion] Which framework do we want to use to replace [paper css](https://www.getpapercss.com/)? Bootstrap, Foundation, Bulma, UIkit, Semantic, Materialize, Tailwind, Milligram, Spectre, ...?

- [ ] Update "Home" page UI
- [ ] Update "Submit Talk" page UI
- [ ] Update "Schedule" page UI
- [ ] Update "Reviewers" page UI
- [ ] Update "Review" page UI
- [ ] Update "Leaderboard" page UI
- [ ] Update "Profile" page UI

**Comment by Rahulbaran** [comment]
Can we use custom CSS (Personally, I prefer)???

**Comment by miquelvir** [comment]
I don't mind, but ask for inpu @app-inv

**Comment by Abdur-rahmaanJ** [comment]
Excuse the interruption, i am taking up the issue

**Comment by Abdur-rahmaanJ** [comment]
We must break up the issue, home completed
