### ISSUE TITLE
Bug: Wrong page return after edit name in profile

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [FlaskCon/traveller#77]
Steps to reproduce:

- Go to profile page
- Select profile tab
- Edit name
- Save
- Redirects to empty page

**Comment by freeearth** [comment]
Will check it out. Actually, didn`t see such behaviour.

**Comment by Abdur-rahmaanJ** [comment]
@freeearth redirects to talks tab but with no talks, going back via profile shows talks there

**Comment by freeearth** [comment]
Great)
